# Generated by Django 5.1.6 on 2025-02-26 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpochItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base', models.CharField(max_length=50)),
                ('rarity', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_found', models.BooleanField(default=False)),
                ('date_found', models.DateField(null=True)),
                ('grail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EpochGrail.grail')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EpochGrail.epochitem')),
            ],
        ),
    ]
